"""虚构排放源与气象情景（教学用，非真实设施）。"""
from __future__ import annotations

SEED_SOURCES = [
    {
        "id": 1,
        "name": "虚构·华北示范热电厂 #1",
        "pollutant": "SO2",
        "lon": 116.40,
        "lat": 39.90,
        "stack_height_m": 120.0,
        "emission_rate_g_s": 50.0,
        "stack_diameter_m": 4.0,
        "exit_velocity_ms": 18.0,
        "stack_temp_k": 410.0,
    },
    {
        "id": 2,
        "name": "虚构·滨江化工厂工艺加热炉",
        "pollutant": "NOx",
        "lon": 119.80,
        "lat": 31.30,
        "stack_height_m": 45.0,
        "emission_rate_g_s": 8.0,
        "stack_diameter_m": 1.2,
        "exit_velocity_ms": 15.0,
        "stack_temp_k": 395.0,
    },
    {
        "id": 3,
        "name": "虚构·西部水泥厂窑尾排气筒",
        "pollutant": "PM10",
        "lon": 103.85,
        "lat": 36.05,
        "stack_height_m": 80.0,
        "emission_rate_g_s": 12.0,
        "stack_diameter_m": 2.2,
        "exit_velocity_ms": 14.0,
        "stack_temp_k": 380.0,
    },
]

SEED_METEOROLOGY = [
    {
        "id": 1,
        "name": "白天·中性大风（D）",
        "wind_from_deg": 270.0,
        "wind_speed_ms": 6.0,
        "stability_class": "D",
        "ambient_temp_k": 293.15,
        "pressure_hpa": 1013.0,
        "background_conc_ug_m3": 15.0,
    },
    {
        "id": 2,
        "name": "晴天午后·不稳定（B）",
        "wind_from_deg": 180.0,
        "wind_speed_ms": 3.0,
        "stability_class": "B",
        "ambient_temp_k": 303.15,
        "pressure_hpa": 1010.0,
        "background_conc_ug_m3": 8.0,
    },
    {
        "id": 3,
        "name": "夜间晴空·稳定（F）",
        "wind_from_deg": 45.0,
        "wind_speed_ms": 2.0,
        "stability_class": "F",
        "ambient_temp_k": 283.15,
        "pressure_hpa": 1018.0,
        "background_conc_ug_m3": 30.0,
    },
    {
        "id": 4,
        "name": "静风情景（应被模型拒绝）",
        "wind_from_deg": 90.0,
        "wind_speed_ms": 0.3,
        "stability_class": "F",
        "ambient_temp_k": 285.15,
        "pressure_hpa": 1016.0,
        "background_conc_ug_m3": 25.0,
    },
    {
        "id": 5,
        "name": "弱风·弱不稳定（C）",
        "wind_from_deg": 315.0,
        "wind_speed_ms": 2.5,
        "stability_class": "C",
        "ambient_temp_k": 298.15,
        "pressure_hpa": 1012.0,
        "background_conc_ug_m3": 12.0,
    },
]
